# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rspec'
require_relative File.join(*%w[.. lib httparty timed])

RSpec.configure do |config|
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end


describe "HTTParty timed" do
  [:get, :post, :delete, :put].each do | method_sym |
    it "#{method_sym.to_s.capitalize}: Makes a request and times it" do
      res = HTTParty.method( method_sym).call( 'http://localhost:4567/hello', {:headers => {'Content-Length' => '0'}})
      res.success?.should eq true
      res.duration.class.should eq Fixnum
    end

  end
end